import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { recordSystemEventOnce } from "@/lib/journal/system-events";

export const dynamic = "force-dynamic";

const FORCE_REASON_MIN = 5;
const FORCE_REASON_MAX = 500;
const NOTES_MAX = 4000;
const MAX_PHOTOS = 12;
const MAX_TASKS = 50;

type Body = {
  tasks_completed?: unknown;
  carer_notes?: string;
  carer_photos?: unknown;
  force_check_out?: boolean;
  force_check_out_reason?: string;
};

/**
 * POST /api/bookings/[id]/timesheet/submit
 *
 * Carer's post-completion submission: tasks ticked off, free-text notes,
 * optional photos, optional forced check-out. Runs AFTER /action?action=complete
 * (which inserts the shift_timesheets row + sets booking.status='completed').
 *
 * Idempotent — re-submitting just updates the same timesheet row. Forced
 * check-out flips `bookings.check_out_forced=true`, `flagged_for_review=true`,
 * `shift_timesheets.forced_check_out=true`, `gps_verified=false` and drops a
 * `departure_forced` journal event.
 */
export async function POST(
  req: Request,
  { params }: { params: Promise<{ id: string }> },
) {
  const { id: bookingId } = await params;
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) {
    return NextResponse.json({ error: "Not authenticated" }, { status: 401 });
  }

  let body: Body;
  try {
    body = (await req.json()) as Body;
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }

  const admin = createAdminClient();

  // Booking must exist, status must be 'completed', caller must be the carer.
  const { data: booking } = await admin
    .from("bookings")
    .select("id, caregiver_id, status, check_out_forced")
    .eq("id", bookingId)
    .maybeSingle<{
      id: string;
      caregiver_id: string | null;
      status: string;
      check_out_forced: boolean | null;
    }>();
  if (!booking) {
    return NextResponse.json({ error: "not_found" }, { status: 404 });
  }
  if (booking.caregiver_id !== user.id) {
    return NextResponse.json({ error: "forbidden" }, { status: 403 });
  }
  if (booking.status !== "completed") {
    return NextResponse.json(
      { error: `booking_must_be_completed_${booking.status}` },
      { status: 400 },
    );
  }

  // Timesheet row must already exist (generated by the complete action).
  const { data: ts } = await admin
    .from("shift_timesheets")
    .select("id, status")
    .eq("booking_id", bookingId)
    .maybeSingle<{ id: string; status: string }>();
  if (!ts) {
    return NextResponse.json({ error: "timesheet_not_found" }, { status: 404 });
  }
  if (ts.status !== "pending_approval") {
    return NextResponse.json(
      { error: `timesheet_locked_${ts.status}` },
      { status: 400 },
    );
  }

  // Sanitise inputs.
  const tasks: string[] = Array.isArray(body.tasks_completed)
    ? (body.tasks_completed as unknown[])
        .filter((s): s is string => typeof s === "string")
        .map((s) => s.trim())
        .filter((s) => s.length > 0 && s.length <= 280)
        .slice(0, MAX_TASKS)
    : [];

  const notes =
    typeof body.carer_notes === "string"
      ? body.carer_notes.trim().slice(0, NOTES_MAX)
      : null;

  const photos: string[] = Array.isArray(body.carer_photos)
    ? (body.carer_photos as unknown[])
        .filter((s): s is string => typeof s === "string")
        // Only allow paths in the carer's own storage folder, like check-in.
        .filter((s) => s.startsWith(`${user.id}/`))
        .slice(0, MAX_PHOTOS)
    : [];

  const force = body.force_check_out === true;
  const forceReason =
    typeof body.force_check_out_reason === "string"
      ? body.force_check_out_reason.trim()
      : "";

  if (force) {
    if (
      forceReason.length < FORCE_REASON_MIN ||
      forceReason.length > FORCE_REASON_MAX
    ) {
      return NextResponse.json(
        {
          error: `force_check_out_reason must be ${FORCE_REASON_MIN}–${FORCE_REASON_MAX} characters.`,
        },
        { status: 400 },
      );
    }
  }

  // Apply forced-check-out to booking row first so subsequent reads see it.
  if (force) {
    await admin
      .from("bookings")
      .update({
        check_out_forced: true,
        check_out_forced_reason: forceReason,
        flagged_for_review: true,
        updated_at: new Date().toISOString(),
      })
      .eq("id", bookingId);
  }

  // Update the timesheet row (idempotent).
  const tsUpdate: Record<string, unknown> = {
    tasks_completed: tasks,
    carer_notes: notes,
    carer_photos: photos,
    updated_at: new Date().toISOString(),
  };
  if (force) {
    tsUpdate.forced_check_out = true;
    tsUpdate.gps_verified = false;
  }
  const { error: updErr } = await admin
    .from("shift_timesheets")
    .update(tsUpdate)
    .eq("id", ts.id);
  if (updErr) {
    return NextResponse.json({ error: updErr.message }, { status: 500 });
  }

  if (force) {
    try {
      const { data: prof } = await admin
        .from("caregiver_profiles")
        .select("display_name")
        .eq("user_id", user.id)
        .maybeSingle<{ display_name: string | null }>();
      await recordSystemEventOnce(admin, {
        bookingId,
        kind: "departure_forced",
        actorName: prof?.display_name ?? null,
        authorId: user.id,
        forceReason,
      });
    } catch (e) {
      console.error("[timesheet.submit] journal event failed", e);
    }
  }

  return NextResponse.json({
    ok: true,
    timesheet_id: ts.id,
    forced_check_out: force,
  });
}
