#!/usr/bin/env bash
# Configure Android release signing for Codemagic CI builds.
#
# Generates android/app/signing.release.gradle (CI-only, gitignored) and
# idempotently appends `apply from: 'signing.release.gradle'` to
# android/app/build.gradle. Passwords are read via System.getenv(...) in
# Gradle — never interpolated into the generated file.
#
# Usage:
#   scripts/ci/setup-android-signing.sh              # android-build: skip if no CM_KEYSTORE
#   scripts/ci/setup-android-signing.sh --require-release   # android-internal: fail or bootstrap
#
# Bootstrap (one-time only, android-internal manual builds):
#   Set ALLOW_KEYSTORE_BOOTSTRAP=true on a single manual android-internal build
#   (--require-release). android-build on main must never bootstrap.
#   Copy the printed CM_KEYSTORE / password values into the android_keystore
#   group, then unset ALLOW_KEYSTORE_BOOTSTRAP.
set -euo pipefail

REQUIRE_RELEASE=0
if [ "${1:-}" = "--require-release" ]; then
  REQUIRE_RELEASE=1
fi

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
KEYSTORE_PATH="/tmp/keystore.jks"
SIGNING_GRADLE="$ROOT/android/app/signing.release.gradle"
BUILD_GRADLE="$ROOT/android/app/build.gradle"

if [ ! -f "$BUILD_GRADLE" ]; then
  echo "❌ $BUILD_GRADLE not found — run cap add android first"
  exit 1
fi

fail_missing_keystore() {
  cat >&2 <<'EOF'
❌ Release signing required but CM_KEYSTORE is not set.

   android-internal (Play upload) builds need the Codemagic android_keystore group:
     CM_KEYSTORE            base64-encoded upload keystore (.jks)
     CM_KEYSTORE_PASSWORD   store password
     CM_KEY_ALIAS           key alias (default: specialcarer)
     CM_KEY_PASSWORD        key password

   One-time bootstrap only: run a single manual build with
     ALLOW_KEYSTORE_BOOTSTRAP=true
   Copy the printed values into android_keystore, then remove
   ALLOW_KEYSTORE_BOOTSTRAP. Normal CI must not set it.

   android-build on main pushes does not require release signing.
EOF
  exit 1
}

bootstrap_keystore() {
  local key_alias="${CM_KEY_ALIAS:-specialcarer}"
  local keystore_password key_password local_keystore cm_keystore_b64

  keystore_password="$(openssl rand -hex 16)"
  # PKCS12 keystores (default for modern keytool) use one password for store + key.
  key_password="$keystore_password"
  local_keystore="$(mktemp /tmp/specialcarer-upload-XXXXXX.jks)"
  rm -f "$local_keystore"

  keytool -genkeypair -v \
    -keystore "$local_keystore" \
    -alias "$key_alias" \
    -keyalg RSA -keysize 2048 -validity 10000 \
    -storepass "$keystore_password" \
    -keypass "$key_password" \
    -dname "CN=Special Carer, OU=Mobile, O=All Care 4 U Group Ltd, L=London, C=GB"

  cp "$local_keystore" "$KEYSTORE_PATH"
  rm -f "$local_keystore"

  # Persist generated credentials for subsequent CI steps in this build.
  if [ -n "${CM_ENV:-}" ]; then
    {
      echo "CM_KEYSTORE_PASSWORD=$keystore_password"
      echo "CM_KEY_PASSWORD=$key_password"
      echo "CM_KEY_ALIAS=$key_alias"
    } >> "$CM_ENV"
  else
    export CM_KEYSTORE_PASSWORD="$keystore_password"
    export CM_KEY_PASSWORD="$key_password"
    export CM_KEY_ALIAS="$key_alias"
  fi

  if base64 --help 2>&1 | grep -q -- '-w'; then
    cm_keystore_b64="$(base64 -w0 "$KEYSTORE_PATH")"
  else
    cm_keystore_b64="$(base64 < "$KEYSTORE_PATH" | tr -d '\n')"
  fi

  cat <<EOF

=================================================================
📋 ONE-TIME KEYSTORE BOOTSTRAP — copy into Codemagic (android_keystore group):

  CM_KEYSTORE            = (base64 block below — mark as secure)
  CM_KEYSTORE_PASSWORD   = $keystore_password
  CM_KEY_ALIAS           = $key_alias
  CM_KEY_PASSWORD        = $keystore_password  (same as store — PKCS12 requires identical)

After saving, unset ALLOW_KEYSTORE_BOOTSTRAP. Future builds reuse CM_KEYSTORE.
=================================================================
$cm_keystore_b64
=================================================================
EOF
}

materialize_keystore_from_env() {
  if base64 --help 2>&1 | grep -q -- '-d'; then
    printf '%s' "$CM_KEYSTORE" | base64 --decode > "$KEYSTORE_PATH"
  else
    printf '%s' "$CM_KEYSTORE" | base64 -d > "$KEYSTORE_PATH"
  fi
  echo "✅ Decoded CM_KEYSTORE to $KEYSTORE_PATH"
}

write_signing_gradle() {
  cat > "$SIGNING_GRADLE" <<'GRADLE_EOF'
// Generated by scripts/ci/setup-android-signing.sh — do not commit.
android {
    signingConfigs {
        release {
            storeFile file('/tmp/keystore.jks')
            storePassword System.getenv('CM_KEYSTORE_PASSWORD') ?: ''
            keyAlias System.getenv('CM_KEY_ALIAS') ?: 'specialcarer'
            keyPassword System.getenv('CM_KEY_PASSWORD') ?: ''
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }
}
GRADLE_EOF
  echo "✅ Wrote $SIGNING_GRADLE"
}

inject_apply_from() {
  if grep -q "signing.release.gradle" "$BUILD_GRADLE"; then
    echo "✅ build.gradle already applies signing.release.gradle"
    return 0
  fi

  cat >> "$BUILD_GRADLE" <<'EOF'

// CI release signing — generated by scripts/ci/setup-android-signing.sh
apply from: 'signing.release.gradle'
EOF
  echo "✅ Appended apply from: 'signing.release.gradle' to build.gradle"
}

if [ -n "${CM_KEYSTORE:-}" ]; then
  materialize_keystore_from_env
  write_signing_gradle
  inject_apply_from
  exit 0
fi

if [ "${ALLOW_KEYSTORE_BOOTSTRAP:-}" = "true" ] && [ "$REQUIRE_RELEASE" -ne 1 ]; then
  echo "⚠️  ALLOW_KEYSTORE_BOOTSTRAP is set but this is not a release-required build — ignoring."
  echo "    android-build on main never bootstraps. Use a manual android-internal build only."
fi

if [ "${ALLOW_KEYSTORE_BOOTSTRAP:-}" = "true" ] && [ "$REQUIRE_RELEASE" -eq 1 ]; then
  echo "⚠️  ALLOW_KEYSTORE_BOOTSTRAP=true — generating one-time upload keystore"
  bootstrap_keystore
  write_signing_gradle
  inject_apply_from
  exit 0
fi

if [ "$REQUIRE_RELEASE" -eq 1 ]; then
  fail_missing_keystore
fi

echo "ℹ️  No CM_KEYSTORE — android-build uses debug signing (no Play upload)"
