import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/admin";
import { generateConsentPdf } from "@/lib/references/generate-consent-pdf";
import { normaliseNationalInsuranceNumber, UK_NI_RE, type ReferenceConsent } from "@/lib/references/consent";
export const dynamic = "force-dynamic";
type Body = { full_name?: string; date_of_birth?: string; national_insurance_number?: string; signature_data_url?: string };
async function session() { const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); return { supabase, user }; }

export async function GET() { const { supabase, user } = await session(); if (!user) return NextResponse.json({ error: "Not authenticated" }, { status: 401 }); const { data, error } = await supabase.from("carer_reference_consents").select("*").eq("carer_id", user.id).maybeSingle<ReferenceConsent>(); return error ? NextResponse.json({ error: error.message }, { status: 500 }) : NextResponse.json({ consent: data }); }
export async function POST(req: Request) {
  const { supabase, user } = await session(); if (!user) return NextResponse.json({ error: "Not authenticated" }, { status: 401 }); let body: Body; try { body = await req.json() as Body; } catch { return NextResponse.json({ error: "Invalid JSON" }, { status: 400 }); }
  const fullName = typeof body.full_name === "string" ? body.full_name.trim() : ""; const dob = typeof body.date_of_birth === "string" ? body.date_of_birth : ""; const ni = normaliseNationalInsuranceNumber(typeof body.national_insurance_number === "string" ? body.national_insurance_number : ""); const signature = typeof body.signature_data_url === "string" ? body.signature_data_url : "";
  if (fullName.length < 1 || fullName.length > 120) return NextResponse.json({ error: "Full legal name is required" }, { status: 400 }); if (!/^\d{4}-\d{2}-\d{2}$/.test(dob) || Number.isNaN(new Date(`${dob}T00:00:00Z`).getTime())) return NextResponse.json({ error: "A valid date of birth is required" }, { status: 400 }); if (!UK_NI_RE.test(ni)) return NextResponse.json({ error: "Enter a valid National Insurance number" }, { status: 400 }); if (!signature.startsWith("data:image/png;base64,") || signature.length > 200000) return NextResponse.json({ error: "A signature is required" }, { status: 400 });
  const ip = req.headers.get("x-forwarded-for")?.split(",")[0]?.trim() || req.headers.get("x-real-ip") || null; const ua = req.headers.get("user-agent")?.slice(0, 500) ?? null;
  const { data, error } = await supabase.from("carer_reference_consents").upsert({ carer_id: user.id, full_name: fullName, date_of_birth: dob, national_insurance_number: ni, signature_data_url: signature, signed_at: new Date().toISOString(), signed_ip: ip, signed_ua: ua, revoked_at: null, pdf_storage_path: null }, { onConflict: "carer_id" }).select("*").single<ReferenceConsent>();
  if (error || !data) return NextResponse.json({ error: error?.message ?? "Unable to save consent" }, { status: 500 });
  try { const bytes = await generateConsentPdf(data); const filePath = `${user.id}/consent-${data.id}.pdf`; const admin = createAdminClient(); const { error: uploadError } = await admin.storage.from("reference-consents").upload(filePath, bytes, { contentType: "application/pdf", upsert: true }); if (uploadError) throw uploadError; const { data: updated, error: updateError } = await admin.from("carer_reference_consents").update({ pdf_storage_path: filePath }).eq("id", data.id).select("*").single<ReferenceConsent>(); if (updateError || !updated) throw updateError; return NextResponse.json({ consent: updated }); } catch (err) { console.error("[reference-consents] PDF generation failed", err); return NextResponse.json({ consent: data, warning: "Consent saved but PDF generation is pending" }); }
}
export async function DELETE() { const { supabase, user } = await session(); if (!user) return NextResponse.json({ error: "Not authenticated" }, { status: 401 }); const { error } = await supabase.from("carer_reference_consents").update({ revoked_at: new Date().toISOString() }).eq("carer_id", user.id).is("revoked_at", null); return error ? NextResponse.json({ error: error.message }, { status: 500 }) : NextResponse.json({ ok: true }); }
